"""Runtime scaffolding for dual-loop CNN-FPGA scheduling."""

from __future__ import annotations

from importlib import import_module


_EXPORTS = {
    "BudgetValidationError": "cnn_fpga.runtime.dual_latency_budget",
    "audit_budget": "cnn_fpga.runtime.dual_latency_budget",
    "load_budget": "cnn_fpga.runtime.dual_latency_budget",
    "validate_budget": "cnn_fpga.runtime.dual_latency_budget",
    "TimingFaultScenario": "cnn_fpga.runtime.timing_fault_model",
    "TimingStressConfig": "cnn_fpga.runtime.timing_fault_model",
    "FixedPointStressConfig": "cnn_fpga.runtime.fixed_point_chain",
    "LUTParameterBank": "cnn_fpga.runtime.fixed_point_chain",
    "PrecisionProfile": "cnn_fpga.runtime.fixed_point_chain",
    "UniformCodeFormat": "cnn_fpga.runtime.fixed_point_chain",
    "run_fixed_point_validation": "cnn_fpga.runtime.fixed_point_chain",
    "default_scenarios": "cnn_fpga.runtime.timing_fault_model",
    "run_timing_fault_validation": "cnn_fpga.runtime.timing_fault_model",
    "simulate_scenario": "cnn_fpga.runtime.timing_fault_model",
    "LatencyInjector": "cnn_fpga.runtime.latency_injector",
    "LatencyContext": "cnn_fpga.runtime.latency_injector",
    "LatencySample": "cnn_fpga.runtime.latency_injector",
    "StageLatencySpec": "cnn_fpga.runtime.latency_injector",
    "FastLoopConfig": "cnn_fpga.runtime.fast_loop_emulator",
    "FastLoopEmulator": "cnn_fpga.runtime.fast_loop_emulator",
    "NoiseProvider": "cnn_fpga.runtime.fast_loop_emulator",
    "ArtifactHistogramPredictor": "cnn_fpga.runtime.inference_service",
    "BaseHistogramPredictor": "cnn_fpga.runtime.inference_service",
    "InferenceService": "cnn_fpga.runtime.inference_service",
    "InferenceServiceConfig": "cnn_fpga.runtime.inference_service",
    "InferenceServiceError": "cnn_fpga.runtime.inference_service",
    "InProcInferenceService": "cnn_fpga.runtime.inference_service",
    "SubprocessInferenceService": "cnn_fpga.runtime.inference_service",
    "TFLiteHistogramPredictor": "cnn_fpga.runtime.inference_service",
    "build_inference_service": "cnn_fpga.runtime.inference_service",
    "resolve_model_path": "cnn_fpga.runtime.inference_service",
    "CommitResult": "cnn_fpga.runtime.param_bank",
    "DecoderRuntimeParams": "cnn_fpga.runtime.param_bank",
    "ParamBank": "cnn_fpga.runtime.param_bank",
    "ParametricMAPLUTConfig": "cnn_fpga.runtime.parametric_map_lut",
    "ParametricMAPLUTDecision": "cnn_fpga.runtime.parametric_map_lut",
    "ParametricMAPLUTImage": "cnn_fpga.runtime.parametric_map_lut",
    "ParametricMAPLUTInput": "cnn_fpga.runtime.parametric_map_lut",
    "ParametricMAPLUTPipeline": "cnn_fpga.runtime.parametric_map_lut",
    "ParametricMAPLUTRuntime": "cnn_fpga.runtime.parametric_map_lut",
    "ExperimentalEventFSM": "cnn_fpga.runtime.experimental_event_fsm",
    "ExperimentalEventFSMConfig": "cnn_fpga.runtime.experimental_event_fsm",
    "ExperimentalEventFSMState": "cnn_fpga.runtime.experimental_event_fsm",
    "ExperimentalEventInput": "cnn_fpga.runtime.experimental_event_fsm",
    "ExperimentalHardwareAction": "cnn_fpga.runtime.experimental_event_fsm",
    "ConservativeFallbackAction": "cnn_fpga.runtime.conservative_fallback",
    "ConservativeFallbackConfig": "cnn_fpga.runtime.conservative_fallback",
    "ConservativeFallbackController": "cnn_fpga.runtime.conservative_fallback",
    "ConservativeFallbackInput": "cnn_fpga.runtime.conservative_fallback",
    "ConservativeFallbackState": "cnn_fpga.runtime.conservative_fallback",
    "TrustedParameterImage": "cnn_fpga.runtime.conservative_fallback",
    "BitAccurateFastPath": "cnn_fpga.runtime.fast_path_fixed_point",
    "FastPathBitAccurateResult": "cnn_fpga.runtime.fast_path_fixed_point",
    "FastPathCodeInput": "cnn_fpga.runtime.fast_path_fixed_point",
    "FastPathFixedPointContract": "cnn_fpga.runtime.fast_path_fixed_point",
    "build_code_input_from_replay": "cnn_fpga.runtime.fast_path_fixed_point",
    "ThreeTimescaleCadenceConfig": "cnn_fpga.runtime.three_timescale_cadence",
    "AdaptationLagRecord": "cnn_fpga.runtime.three_timescale_cadence",
    "RecalibrationTrigger": "cnn_fpga.runtime.three_timescale_cadence",
    "ThreeTimescaleCadence": "cnn_fpga.runtime.three_timescale_cadence",
    "AtomicParameterBankConfig": "cnn_fpga.runtime.atomic_parameter_bank",
    "AtomicParameterBankError": "cnn_fpga.runtime.atomic_parameter_bank",
    "AtomicParameterImageBank": "cnn_fpga.runtime.atomic_parameter_bank",
    "ParameterImageManifest": "cnn_fpga.runtime.atomic_parameter_bank",
    "SelectionHysteresisState": "cnn_fpga.runtime.atomic_parameter_bank",
    "StagedParameterImage": "cnn_fpga.runtime.atomic_parameter_bank",
    "CommitAck": "cnn_fpga.runtime.atomic_parameter_bank",
    "ActiveImageReadback": "cnn_fpga.runtime.atomic_parameter_bank",
    "build_parameter_image_manifest": "cnn_fpga.runtime.atomic_parameter_bank",
    "seal_parameter_image_manifest": "cnn_fpga.runtime.atomic_parameter_bank",
    "serialize_parameter_image": "cnn_fpga.runtime.atomic_parameter_bank",
    "deserialize_parameter_image": "cnn_fpga.runtime.atomic_parameter_bank",
    "verify_commit_ack_readback": "cnn_fpga.runtime.atomic_parameter_bank",
    "ClosedLoopRecoveryConfig": "cnn_fpga.runtime.closed_loop_fault_recovery",
    "ClosedLoopCycleInput": "cnn_fpga.runtime.closed_loop_fault_recovery",
    "UpdateAttempt": "cnn_fpga.runtime.closed_loop_fault_recovery",
    "ClosedLoopCycleRecord": "cnn_fpga.runtime.closed_loop_fault_recovery",
    "ClosedLoopFaultRecoverySupervisor": "cnn_fpga.runtime.closed_loop_fault_recovery",
    "parameter_image_semantics_sha256": "cnn_fpga.runtime.closed_loop_fault_recovery",
    "PendingCommit": "cnn_fpga.runtime.param_bank",
    "ParameterUpdateConflictError": "cnn_fpga.runtime.param_bank",
    "RunLengthFSMConfig": "cnn_fpga.runtime.run_length_fsm",
    "RunLengthFSMDecision": "cnn_fpga.runtime.run_length_fsm",
    "RunLengthFSMInput": "cnn_fpga.runtime.run_length_fsm",
    "RunLengthFSMState": "cnn_fpga.runtime.run_length_fsm",
    "RunLengthParameterBankFSM": "cnn_fpga.runtime.run_length_fsm",
    "RunLengthParameterTable": "cnn_fpga.runtime.run_length_fsm",
    "ARITHMETIC_MODES": "cnn_fpga.runtime.exponential_recurrence",
    "ExponentialEventControllerConfig": "cnn_fpga.runtime.exponential_recurrence",
    "ExponentialEventDecision": "cnn_fpga.runtime.exponential_recurrence",
    "ExponentialRecurrenceEventController": "cnn_fpga.runtime.exponential_recurrence",
    "ExponentialSaturationKernel": "cnn_fpga.runtime.exponential_recurrence",
    "DualLoopScheduler": "cnn_fpga.runtime.scheduler",
    "SchedulerConfig": "cnn_fpga.runtime.scheduler",
    "SchedulerEvent": "cnn_fpga.runtime.scheduler",
    "SlowUpdateJob": "cnn_fpga.runtime.scheduler",
    "WindowFrame": "cnn_fpga.runtime.scheduler",
    "SlowLoopRuntime": "cnn_fpga.runtime.slow_loop_runtime",
    "SlowLoopRuntimeConfig": "cnn_fpga.runtime.slow_loop_runtime",
    "SlowLoopRuntimeError": "cnn_fpga.runtime.slow_loop_runtime",
    "PhysicalNoiseBridge": "cnn_fpga.runtime.noise_bridge",
    "PhysicalNoiseBridgeConfig": "cnn_fpga.runtime.noise_bridge",
    "maybe_build_physical_noise_bridge": "cnn_fpga.runtime.noise_bridge",
}

__all__ = list(_EXPORTS)


def __getattr__(name: str):
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value
