"""physics 包的对外统一入口（惰性加载层）。

设计目的：
- physics 子模块（gkp_state、noise_channels、syndrome_measurement、
  error_correction、logical_tracking）之间存在依赖，且部分子模块会尝试导入
  较重的第三方库（如 Strawberry Fields）。为了避免 ``import physics`` 时一次性
  把所有子模块及其依赖全部加载，本文件通过模块级 ``__getattr__`` 实现"按需惰性加载"：
  只有在真正访问某个公开符号时，才导入它所在的子模块。

约定：
- ``_EXPORTS`` 字典维护"公开符号名 -> 所在子模块"的映射；
- ``__all__`` 由 ``_EXPORTS`` 的键自动生成，用于 ``from physics import *``；
- 首次访问某符号后，结果会缓存到模块 globals()，后续访问不再重复导入。
"""

from __future__ import annotations

from importlib import import_module


# 公开符号 -> 所在子模块的映射。新增导出符号时只需在此登记。
_EXPORTS = {
    "ApproximateGKPState": "physics.gkp_state",
    "GKPStateFactory": "physics.gkp_state",
    "QuantumNoiseChannel": "physics.noise_channels",
    "PhotonLossChannel": "physics.noise_channels",
    "ThermalNoiseChannel": "physics.noise_channels",
    "SyndromeMeasurement": "physics.syndrome_measurement",
    "RealisticSyndromeMeasurement": "physics.syndrome_measurement",
    "GKPErrorCorrector": "physics.error_correction",
    "LinearDecoder": "physics.error_correction",
    "LogicalErrorTracker": "physics.logical_tracking",
    "StandardBinningResult": "physics.ideal_gkp_decoder",
    "MAPDecodeResult": "physics.ideal_gkp_decoder",
    "MAPDecode2DResult": "physics.ideal_gkp_decoder",
    "standard_binning_1d": "physics.ideal_gkp_decoder",
    "gaussian_logical_flip_probability": "physics.ideal_gkp_decoder",
    "coset_likelihood_1d": "physics.ideal_gkp_decoder",
    "llr_1d": "physics.ideal_gkp_decoder",
    "map_decode_1d": "physics.ideal_gkp_decoder",
    "decode_1d": "physics.ideal_gkp_decoder",
    "covariance_from_sigmas": "physics.ideal_gkp_decoder",
    "coset_likelihood_2d": "physics.ideal_gkp_decoder",
    "map_decode_2d": "physics.ideal_gkp_decoder",
    "independent_map_decode_2d": "physics.ideal_gkp_decoder",
    "PeakTable": "physics.finite_energy_gkp",
    "SyndromeDistribution": "physics.finite_energy_gkp",
    "WignerLikeGrid": "physics.finite_energy_gkp",
    "FiniteEnergyGKPState": "physics.finite_energy_gkp",
    "gaussian_envelope_state": "physics.finite_energy_gkp",
    "damped_projector_state": "physics.finite_energy_gkp",
    "PauliChannel": "physics.logical_channel",
    "ParityResponse1D": "physics.logical_channel",
    "ParityConfusion": "physics.logical_channel",
    "pauli_channel_from_residual_distribution": "physics.logical_channel",
    "pauli_channel_from_parity_samples": "physics.logical_channel",
    "pauli_channel_from_joint_confusion": "physics.logical_channel",
    "pauli_channel_from_axis_confusions": "physics.logical_channel",
    "finite_energy_parity_response_1d": "physics.logical_channel",
    "parity_confusion_from_response": "physics.logical_channel",
    "ShrinkageTrendConfig": "physics.finite_energy_trends",
    "ShrinkageTrendPoint": "physics.finite_energy_trends",
    "ShrinkageTrendResult": "physics.finite_energy_trends",
    "run_finite_energy_shrinkage_trend": "physics.finite_energy_trends",
    "DriftState": "physics.drift_processes",
    "DriftProcess": "physics.drift_processes",
    "ConstantDriftProcess": "physics.drift_processes",
    "MeanDriftProcess": "physics.drift_processes",
    "VarianceDriftProcess": "physics.drift_processes",
    "LossDriftProcess": "physics.drift_processes",
    "OutlierRateDriftProcess": "physics.drift_processes",
    "StepDriftProcess": "physics.drift_processes",
    "TelegraphDriftProcess": "physics.drift_processes",
    "BurstDriftProcess": "physics.drift_processes",
    "sample_displacements": "physics.drift_processes",
    "LegacyRunWithDriftAdapter": "physics.drift_processes",
    "as_run_with_drift_callback": "physics.drift_processes",
    "OracleMAPResult": "physics.oracle_map",
    "OracleTrajectoryResult": "physics.oracle_map",
    "oracle_log_likelihoods_2d": "physics.oracle_map",
    "oracle_map_2d": "physics.oracle_map",
    "oracle_map": "physics.oracle_map",
    "oracle_map_trajectory": "physics.oracle_map",
    "OracleGapPointEstimate": "physics.oracle_gap",
    "PairedDifferenceInterval": "physics.oracle_gap",
    "OracleGapMetrics": "physics.oracle_gap",
    "oracle_gap_from_rates": "physics.oracle_gap",
    "compute_oracle_gap_metrics": "physics.oracle_gap",
    "PauliFrame": "physics.sbs_error_space",
    "SBSInstrumentResult": "physics.sbs_error_space",
    "SBSPopulationResult": "physics.sbs_error_space",
    "SBSTrajectory": "physics.sbs_error_space",
    "SBSErrorSpaceInstrument": "physics.sbs_error_space",
    "make_trickle_down_chain": "physics.sbs_error_space",
    "embed_logical_state": "physics.sbs_error_space",
    "PairedSyndrome": "physics.sbs_observation_reset",
    "HiddenAncillaMemory": "physics.sbs_observation_reset",
    "ObservedSyndromeMemory": "physics.sbs_observation_reset",
    "SBSObservedCycle": "physics.sbs_observation_reset",
    "SBSTruthCycle": "physics.sbs_observation_reset",
    "SBSObservationResetStep": "physics.sbs_observation_reset",
    "SBSObservationResetTrajectory": "physics.sbs_observation_reset",
    "SBSObservationResetModel": "physics.sbs_observation_reset",
    "ideal_syndrome_from_kraus": "physics.sbs_observation_reset",
    "make_persistent_leakage_model": "physics.sbs_observation_reset",
    "CyclePhaseSpec": "physics.sbs_cycle_state_machine",
    "SBSCycleTimingProfile": "physics.sbs_cycle_state_machine",
    "SBSConstituentControl": "physics.sbs_cycle_state_machine",
    "CycleEvent": "physics.sbs_cycle_state_machine",
    "SBSConstituentCycleTrace": "physics.sbs_cycle_state_machine",
    "SBSFullXZCycleTrace": "physics.sbs_cycle_state_machine",
    "SBSConstituentRuntime": "physics.sbs_cycle_state_machine",
    "SBSCycleStateMachine": "physics.sbs_cycle_state_machine",
    "sivak_table_s3_profile": "physics.sbs_cycle_state_machine",
    "DisplacementFaultSweepConfig": "physics.sbs_displacement_fault",
    "MeanEstimate": "physics.sbs_displacement_fault",
    "DisplacementTrendPoint": "physics.sbs_displacement_fault",
    "TrendCheck": "physics.sbs_displacement_fault",
    "DisplacementTrendGate": "physics.sbs_displacement_fault",
    "DisplacementFaultSweepResult": "physics.sbs_displacement_fault",
    "distance_to_closest_logical_operation": "physics.sbs_displacement_fault",
    "run_displacement_fault_sweep": "physics.sbs_displacement_fault",
    "write_displacement_fault_report": "physics.sbs_displacement_fault",
    "OccupancyCorrelationConfig": "physics.sbs_occupancy_correlation",
    "OccupancyDataset": "physics.sbs_occupancy_correlation",
    "IntervalEstimate": "physics.sbs_occupancy_correlation",
    "SyndromeOccupancyEstimate": "physics.sbs_occupancy_correlation",
    "TailCorrelationEstimate": "physics.sbs_occupancy_correlation",
    "OccupancyCorrelationCheck": "physics.sbs_occupancy_correlation",
    "OccupancyCorrelationGate": "physics.sbs_occupancy_correlation",
    "OccupancyCorrelationResult": "physics.sbs_occupancy_correlation",
    "simulate_occupancy_correlation_dataset": "physics.sbs_occupancy_correlation",
    "estimate_occupancy_from_syndrome": "physics.sbs_occupancy_correlation",
    "estimate_leakage_tail_correlation": "physics.sbs_occupancy_correlation",
    "run_occupancy_correlation_validation": "physics.sbs_occupancy_correlation",
    "write_occupancy_correlation_report": "physics.sbs_occupancy_correlation",
    "SyndromeStreamConfig": "physics.syndrome_stream",
    "ObservedSyndromeStep": "physics.syndrome_stream",
    "SyndromeTruthStep": "physics.syndrome_stream",
    "SyndromeStreamStep": "physics.syndrome_stream",
    "SyndromeStream": "physics.syndrome_stream",
    "generate_syndrome_stream": "physics.syndrome_stream",
    "ControlMemoryConfig": "physics.control_memory",
    "ControlDecision": "physics.control_memory",
    "ControlMemoryState": "physics.control_memory",
    "ControlMemoryUpdate": "physics.control_memory",
    "ControlMemoryTrajectory": "physics.control_memory",
    "MultiRoundControlMemory": "physics.control_memory",
    "FastMonteCarloConfig": "physics.fast_monte_carlo",
    "RareEventSpec": "physics.fast_monte_carlo",
    "MonteCarloStratumResult": "physics.fast_monte_carlo",
    "FastMonteCarloResult": "physics.fast_monte_carlo",
    "run_fast_monte_carlo": "physics.fast_monte_carlo",
    "write_fast_monte_carlo_report": "physics.fast_monte_carlo",
    "EnvelopeIndexDistribution": "physics.finite_squeezing_noise",
    "FiniteSqueezingNoiseConfig": "physics.finite_squeezing_noise",
    "FiniteSqueezingNoiseBudget": "physics.finite_squeezing_noise",
    "FiniteSqueezingNoiseSummary": "physics.finite_squeezing_noise",
    "FiniteSqueezingNoiseBatch": "physics.finite_squeezing_noise",
    "FiniteSqueezingSweepPoint": "physics.finite_squeezing_noise",
    "FiniteSqueezingSweepResult": "physics.finite_squeezing_noise",
    "isolated_peak_variance": "physics.finite_squeezing_noise",
    "envelope_index_distribution": "physics.finite_squeezing_noise",
    "finite_squeezing_noise_budget": "physics.finite_squeezing_noise",
    "sample_finite_squeezing_noise": "physics.finite_squeezing_noise",
    "run_high_squeezing_limit_sweep": "physics.finite_squeezing_noise",
    "write_finite_squeezing_report": "physics.finite_squeezing_noise",
    "SBSFaultOverlayConfig": "physics.protocol_ancilla_errors",
    "SBSAncillaFaultEvent": "physics.protocol_ancilla_errors",
    "SBSFaultOverlayTruth": "physics.protocol_ancilla_errors",
    "SBSFaultOverlayStep": "physics.protocol_ancilla_errors",
    "SBSFaultOverlayTrajectory": "physics.protocol_ancilla_errors",
    "SBSAncillaFaultOverlay": "physics.protocol_ancilla_errors",
    "SharpenTrimAncillaConfig": "physics.protocol_ancilla_errors",
    "SharpenTrimMemory": "physics.protocol_ancilla_errors",
    "SharpenTrimObservedRound": "physics.protocol_ancilla_errors",
    "SharpenTrimTruthRound": "physics.protocol_ancilla_errors",
    "SharpenTrimStep": "physics.protocol_ancilla_errors",
    "SharpenTrimTrajectory": "physics.protocol_ancilla_errors",
    "SharpenTrimAncillaModel": "physics.protocol_ancilla_errors",
    "SecondaryProtocolNoiseSpec": "physics.protocol_ancilla_errors",
    "secondary_protocol_noise_specs": "physics.protocol_ancilla_errors",
    "ProtocolAncillaValidationResult": "physics.protocol_ancilla_errors",
    "run_protocol_ancilla_validation": "physics.protocol_ancilla_errors",
    "write_protocol_ancilla_validation": "physics.protocol_ancilla_errors",
    "ControlImperfectionConfig": "physics.control_imperfections",
    "ControlActionRequest": "physics.control_imperfections",
    "ControlActionRecord": "physics.control_imperfections",
    "ControlActionTruth": "physics.control_imperfections",
    "ControlImperfectionStep": "physics.control_imperfections",
    "ControlImperfectionTrajectory": "physics.control_imperfections",
    "ControlImperfectionBatch": "physics.control_imperfections",
    "ControlImperfectionModel": "physics.control_imperfections",
    "ControlImperfectionValidationResult": "physics.control_imperfections",
    "ideal_control_imperfection_config": "physics.control_imperfections",
    "run_control_imperfection_validation": "physics.control_imperfections",
    "write_control_imperfection_validation": "physics.control_imperfections",
    "CANONICAL_COMMUTATOR": "physics.quadrature_conventions",
    "CANONICAL_LOGICAL_CELL_SPACING": "physics.quadrature_conventions",
    "CANONICAL_STABILIZER_SPACING": "physics.quadrature_conventions",
    "DECODER_LOGICAL_CELL_SPACING": "physics.quadrature_conventions",
    "DECODER_STANDARDIZATION_SCALE": "physics.quadrature_conventions",
    "DISPLACEMENT_LOGICAL_AMPLITUDE": "physics.quadrature_conventions",
    "PAPER_STABILIZER_DISPLACEMENT_AMPLITUDE": "physics.quadrature_conventions",
    "SYMPLECTIC_Q_LOGICAL_CELL_SPACING": "physics.quadrature_conventions",
    "SYMPLECTIC_P_LOGICAL_CELL_SPACING": "physics.quadrature_conventions",
    "QuadratureChart": "physics.quadrature_conventions",
    "QuadratureConventionValidation": "physics.quadrature_conventions",
    "chart_transform": "physics.quadrature_conventions",
    "convert_axis_sigma": "physics.quadrature_conventions",
    "convert_covariance": "physics.quadrature_conventions",
    "convert_phase_vector": "physics.quadrature_conventions",
    "logical_cell_spacing": "physics.quadrature_conventions",
    "run_quadrature_convention_validation": "physics.quadrature_conventions",
    "wavefunction_dilation": "physics.quadrature_conventions",
    "write_quadrature_convention_validation": "physics.quadrature_conventions",
    "FOCK_MODEL_SCOPE": "physics.fock_density_model",
    "FockDiagnostics": "physics.fock_density_model",
    "FiniteCutoffDensity": "physics.fock_density_model",
    "FockPreparationResult": "physics.fock_density_model",
    "ModularMeasurementResult": "physics.fock_density_model",
    "FockDensityValidationResult": "physics.fock_density_model",
    "FiniteCutoffFockModel": "physics.fock_density_model",
    "run_fock_density_validation": "physics.fock_density_model",
    "write_fock_density_validation": "physics.fock_density_model",
    "PAPER_CANONICAL_SOURCE_SCALE": "physics.fock_sbs_cycle",
    "FOCK_SBS_CYCLE_SCOPE": "physics.fock_sbs_cycle",
    "FockIdleConfig": "physics.fock_sbs_cycle",
    "SBSFockCycleConfig": "physics.fock_sbs_cycle",
    "FockCodeBasis": "physics.fock_sbs_cycle",
    "SBSKrausDiagnostics": "physics.fock_sbs_cycle",
    "FockLogicalProjection": "physics.fock_sbs_cycle",
    "SBSFockObservedConstituent": "physics.fock_sbs_cycle",
    "SBSFockTruthConstituent": "physics.fock_sbs_cycle",
    "SBSFockCycleBranch": "physics.fock_sbs_cycle",
    "SBSFockExactCycleResult": "physics.fock_sbs_cycle",
    "SBSCutoffValidationPoint": "physics.fock_sbs_cycle",
    "SBSFockCycleValidationResult": "physics.fock_sbs_cycle",
    "SBSFockOneRoundSimulator": "physics.fock_sbs_cycle",
    "DIFFERENTIABLE_SBS_SCOPE": "physics.differentiable_sbs_trajectory",
    "POROTTI_S1_PROFILE_ID": "physics.differentiable_sbs_trajectory",
    "PARAMETER_NAMES": "physics.differentiable_sbs_trajectory",
    "TrajectoryTimingPhase": "physics.differentiable_sbs_trajectory",
    "DifferentiableSBSTimingProfile": "physics.differentiable_sbs_trajectory",
    "DifferentiableSBSConfig": "physics.differentiable_sbs_trajectory",
    "TrajectoryResourceProfile": "physics.differentiable_sbs_trajectory",
    "DifferentiableTrajectoryResult": "physics.differentiable_sbs_trajectory",
    "nominal_sbs_parameters": "physics.differentiable_sbs_trajectory",
    "DifferentiableSBSTrajectorySimulator": "physics.differentiable_sbs_trajectory",
    "run_differentiable_sbs_validation": "physics.differentiable_sbs_trajectory",
    "FEEDBACK_GRAPE_GRADIENT_SCOPE": "physics.feedback_grape_gradient",
    "COMPACT_POLICY_PARAMETER_NAMES": "physics.feedback_grape_gradient",
    "GradientValidationConfig": "physics.feedback_grape_gradient",
    "CompactHistoryPolicy": "physics.feedback_grape_gradient",
    "ExactGradientDecomposition": "physics.feedback_grape_gradient",
    "FiniteDifferenceGradientResult": "physics.feedback_grape_gradient",
    "MonteCarloGradientResult": "physics.feedback_grape_gradient",
    "enumerate_binary_trajectories": "physics.feedback_grape_gradient",
    "default_policy_parameters": "physics.feedback_grape_gradient",
    "exact_gradient_decomposition": "physics.feedback_grape_gradient",
    "finite_difference_gradient": "physics.feedback_grape_gradient",
    "finite_difference_step_sweep": "physics.feedback_grape_gradient",
    "monte_carlo_gradient_validation": "physics.feedback_grape_gradient",
    "run_feedback_grape_gradient_validation": "physics.feedback_grape_gradient",
    "DIFFERENTIABLE_SBS_FEASIBILITY_SCOPE": "physics.differentiable_sbs_feasibility",
    "POLICY_ARCHITECTURE_ID": "physics.differentiable_sbs_feasibility",
    "RecurrentPolicySpec": "physics.differentiable_sbs_feasibility",
    "TrainingPointConfig": "physics.differentiable_sbs_feasibility",
    "TrainingPointResult": "physics.differentiable_sbs_feasibility",
    "FeasibilityRecurrentPolicy": "physics.differentiable_sbs_feasibility",
    "benchmark_training_point": "physics.differentiable_sbs_feasibility",
    "safe_benchmark_training_point": "physics.differentiable_sbs_feasibility",
    "run_point_subprocess": "physics.differentiable_sbs_feasibility",
    "default_scan_points": "physics.differentiable_sbs_feasibility",
    "validate_production_design": "physics.differentiable_sbs_feasibility",
    "summarize_scan": "physics.differentiable_sbs_feasibility",
    "run_feasibility_scan": "physics.differentiable_sbs_feasibility",
    "NMF_RANKING_SCOPE": "physics.nmf_directional_ranking",
    "DirectionalRankingConfig": "physics.nmf_directional_ranking",
    "PaperScaleMFPolicy": "physics.nmf_directional_ranking",
    "PaperScaleNMFPolicy": "physics.nmf_directional_ranking",
    "NMFLatestOnlyView": "physics.nmf_directional_ranking",
    "build_policy": "physics.nmf_directional_ranking",
    "evaluate_policy": "physics.nmf_directional_ranking",
    "run_directional_ranking": "physics.nmf_directional_ranking",
    "state_dict_sha256": "physics.nmf_directional_ranking",
    "CONTROL_ORACLE_ROLE_ID": "physics.trajectory_lookup_control_oracle",
    "LOOKUP_SCOPE": "physics.trajectory_lookup_control_oracle",
    "TrajectoryLookupConfig": "physics.trajectory_lookup_control_oracle",
    "CausalHistoryLookupPolicy": "physics.trajectory_lookup_control_oracle",
    "TimeIndexedOpenLoopPolicy": "physics.trajectory_lookup_control_oracle",
    "ExactPolicyEvaluation": "physics.trajectory_lookup_control_oracle",
    "OptimizationRun": "physics.trajectory_lookup_control_oracle",
    "history_node_count": "physics.trajectory_lookup_control_oracle",
    "terminal_branch_count": "physics.trajectory_lookup_control_oracle",
    "resource_growth_row": "physics.trajectory_lookup_control_oracle",
    "evaluate_exact_policy": "physics.trajectory_lookup_control_oracle",
    "optimize_policy_multistart": "physics.trajectory_lookup_control_oracle",
    "EXPONENTIAL_RECURRENCE_SCOPE": "physics.exponential_recurrence_control",
    "ExponentialRecurrenceConfig": "physics.exponential_recurrence_control",
    "ExponentialSaturationControlPolicy": "physics.exponential_recurrence_control",
    "FixedPointExponentialPolicy": "physics.exponential_recurrence_control",
    "RecurrenceOptimizationRun": "physics.exponential_recurrence_control",
    "exact_expected_fidelity": "physics.exponential_recurrence_control",
    "optimize_recurrence_multistart": "physics.exponential_recurrence_control",
    "INTERVENTION_MODES": "physics.memory_specific_ablation",
    "MemoryInterventionSpec": "physics.memory_specific_ablation",
    "FrozenMemoryInterventionPolicy": "physics.memory_specific_ablation",
    "logical_density": "physics.fock_sbs_cycle",
    "run_sbs_fock_cycle_validation": "physics.fock_sbs_cycle",
    "write_sbs_fock_cycle_validation": "physics.fock_sbs_cycle",
    "NOISE_TRANSFER_SCOPE": "physics.noise_transfer_surrogate",
    "GaussianAliasStatistics": "physics.noise_transfer_surrogate",
    "NoiseTransferConfig": "physics.noise_transfer_surrogate",
    "NoiseTransferState": "physics.noise_transfer_surrogate",
    "NoiseTransferAxisDiagnostic": "physics.noise_transfer_surrogate",
    "NoiseTransferLogicalJump": "physics.noise_transfer_surrogate",
    "NoiseTransferStepResult": "physics.noise_transfer_surrogate",
    "NoiseTransferSample": "physics.noise_transfer_surrogate",
    "GKPNoiseTransferSurrogate": "physics.noise_transfer_surrogate",
    "NoiseTransferFockAlignmentPoint": "physics.noise_transfer_surrogate",
    "NoiseTransferSweepPoint": "physics.noise_transfer_surrogate",
    "NoiseTransferValidationResult": "physics.noise_transfer_surrogate",
    "squeezing_db_to_peak_variance": "physics.noise_transfer_surrogate",
    "projector_delta_from_squeezing_db": "physics.noise_transfer_surrogate",
    "gaussian_alias_statistics": "physics.noise_transfer_surrogate",
    "fock_q_variance_alignment": "physics.noise_transfer_surrogate",
    "run_noise_transfer_validation": "physics.noise_transfer_surrogate",
    "write_noise_transfer_validation": "physics.noise_transfer_surrogate",
    "CROSS_FIDELITY_SCOPE": "physics.cross_fidelity_validation",
    "DEFAULT_DB_GRID": "physics.cross_fidelity_validation",
    "CrossFidelityConfig": "physics.cross_fidelity_validation",
    "PauliTrendMetrics": "physics.cross_fidelity_validation",
    "FockFoldedResponse": "physics.cross_fidelity_validation",
    "FockProtocolMetrics": "physics.cross_fidelity_validation",
    "FockLaneMetrics": "physics.cross_fidelity_validation",
    "EffectiveLaneMetrics": "physics.cross_fidelity_validation",
    "NoiseTransferLaneMetrics": "physics.cross_fidelity_validation",
    "SyndromeLaneMetrics": "physics.cross_fidelity_validation",
    "CrossFidelityPoint": "physics.cross_fidelity_validation",
    "FockCutoffPoint": "physics.cross_fidelity_validation",
    "ErrorAttribution": "physics.cross_fidelity_validation",
    "CrossFidelityValidationResult": "physics.cross_fidelity_validation",
    "independent_axis_pauli_metrics": "physics.cross_fidelity_validation",
    "fock_folded_map_response": "physics.cross_fidelity_validation",
    "run_cross_fidelity_validation": "physics.cross_fidelity_validation",
    "write_cross_fidelity_validation": "physics.cross_fidelity_validation",
}

__all__ = list(_EXPORTS)


def __getattr__(name: str):
    """模块级惰性属性访问钩子（PEP 562）。

    功能:
        把 ``physics.X`` 或 ``from physics import X`` 解析为对子模块的按需导入——
        只有在真正访问 X 时，才触发对应子模块的 import，并把结果缓存到模块
        ``globals()``，从而避免一次性加载所有子模块及其重依赖。

    输入:
        name: 被访问的属性名，即某个公开符号（如 'ApproximateGKPState'）。

    输出:
        返回该符号在对应子模块中的实际对象；首次解析后缓存，后续访问直接命中缓存。

    异常:
        若 ``name`` 不在 ``_EXPORTS`` 中，抛出 ``AttributeError``，
        提示当前模块没有该属性。
    """
    module_name = _EXPORTS.get(name)
    if module_name is None:
        raise AttributeError(f"module {__name__!r} has no attribute {name!r}")
    module = import_module(module_name)
    value = getattr(module, name)
    globals()[name] = value
    return value
