"""Public façade for the executable Phase-9 causal digital-twin contract.

The implementation is split by responsibility under :mod:`physics._phase9_contract`.
This stable module remains the only supported public import surface.
"""

from __future__ import annotations

from ._phase9_contract.enumeration import (
    factorized_map_manifest,
    reachable_fsm_states,
    reset_distance,
)
from ._phase9_contract.qualification import (
    DecisionReceipt,
    RepresentativeActionProbe,
    _minimal_memory,
    _minimal_observed,
    audit_contract,
    causal_prefix_token,
    deployable_decision,
    execute_representative_probe,
    probe_coverage_witnesses,
    representative_action_probes,
    validate_complete_package_nomination,
)
from ._phase9_contract.recurrence import (
    CanonicalizedKey,
    KeyAssembly,
    assemble_deployable_key,
    canonicalize_composite_key,
    classify_raw_fault,
    fault_response_witnesses,
    nominal_cell,
    total_recurrence,
    transition_cell,
    validate_deployable_inputs,
)
from ._phase9_contract.schema import (
    ACTION_LAYOUT,
    ACTION_SIDEBAND_CONTRACT,
    ACTION_WORD_BITS,
    CLAIM_BOUNDARY,
    CRC16_CONTRACT,
    DISCRIMINATOR_LAYOUT,
    FAULT_PRIORITY,
    FSM_ENCODING,
    INTEGRITY_FLAG_LAYOUT,
    MODEL_SCOPE,
    NAMESPACE_SCHEMAS,
    NOMINAL_CELL_COUNT,
    OBSERVATION_ENVELOPE_BOUNDARY,
    PAYLOAD_BITS,
    PHASE_FRAME_SEMANTICS,
    SLOW_PATH_BOUNDARY,
    TRANSITION_CELL_COUNT,
    TRUTH_PROVENANCE_DENYLIST,
    ActionWord,
    BankId,
    CompositeKey,
    EventClass,
    FsmMode,
    IntegrityStatus,
    NominalAction,
    NominalResult,
    ReasonCode,
    RecurrenceResult,
    TransitionResult,
    canonical_json,
    crc16_ccitt,
    decode_fsm,
    encode_fsm,
    is_legal_discriminator_word,
    legal_discriminator_words,
    validate_namespace,
)


__all__ = [
    "ACTION_LAYOUT",
    "ACTION_SIDEBAND_CONTRACT",
    "ACTION_WORD_BITS",
    "ActionWord",
    "BankId",
    "CLAIM_BOUNDARY",
    "CompositeKey",
    "CRC16_CONTRACT",
    "DISCRIMINATOR_LAYOUT",
    "EventClass",
    "FAULT_PRIORITY",
    "FSM_ENCODING",
    "FsmMode",
    "IntegrityStatus",
    "INTEGRITY_FLAG_LAYOUT",
    "MODEL_SCOPE",
    "NAMESPACE_SCHEMAS",
    "NOMINAL_CELL_COUNT",
    "NominalAction",
    "OBSERVATION_ENVELOPE_BOUNDARY",
    "ReasonCode",
    "PHASE_FRAME_SEMANTICS",
    "SLOW_PATH_BOUNDARY",
    "TRANSITION_CELL_COUNT",
    "TRUTH_PROVENANCE_DENYLIST",
    "assemble_deployable_key",
    "audit_contract",
    "canonicalize_composite_key",
    "causal_prefix_token",
    "classify_raw_fault",
    "crc16_ccitt",
    "decode_fsm",
    "deployable_decision",
    "encode_fsm",
    "execute_representative_probe",
    "factorized_map_manifest",
    "fault_response_witnesses",
    "is_legal_discriminator_word",
    "legal_discriminator_words",
    "nominal_cell",
    "probe_coverage_witnesses",
    "reachable_fsm_states",
    "representative_action_probes",
    "reset_distance",
    "total_recurrence",
    "transition_cell",
    "validate_complete_package_nomination",
    "validate_deployable_inputs",
    "validate_namespace",
]
