"""Build a file-level source-data manifest for the submission draft.

The manifest covers manuscript-facing CSV/JSON source data and plotting or
analysis scripts.  It is intentionally not a recursive hash closure over
historical run directories, and it is not a hardware provenance manifest.
"""

from __future__ import annotations

import csv
import hashlib
import json
from pathlib import Path


ROOT = Path(__file__).resolve().parents[2]
OUT_CSV = ROOT / "docs/paper_materials/submission_draft_source_data_manifest.csv"
OUT_JSON = ROOT / "docs/paper_materials/submission_draft_source_data_manifest.json"


SOURCES = [
    {
        "item_id": "fig02_main_results",
        "manuscript_item": "Figure 2 and main software-HIL table",
        "source_path": "docs/figure_assets/submission_draft_python_figures/source_data_fig02_main_results.csv",
        "derived_from": "preserved four-scenario software-in-the-loop comparison table",
        "source_data_scope": "manuscript figure source data",
        "statistical_boundary": "descriptive mean and SD only",
        "hardware_boundary": "not a board measurement",
        "notes": "Supports protocol-defined final_ler comparison only.",
    },
    {
        "item_id": "fig02_paired_deltas",
        "manuscript_item": "Paired UKF-vs-hybrid descriptive deltas",
        "source_path": "docs/figure_assets/submission_draft_python_figures/source_data_fig02_paired_deltas.csv",
        "derived_from": "paired scenario deltas from preserved comparison rows",
        "source_data_scope": "manuscript figure source data",
        "statistical_boundary": "paired descriptive deltas only",
        "hardware_boundary": "not a board measurement",
        "notes": "Does not provide inferential confidence intervals or p-values.",
    },
    {
        "item_id": "paired_uncertainty",
        "manuscript_item": "Non-inferential paired-bootstrap envelope",
        "source_path": "docs/paper_materials/submission_draft_paired_uncertainty_analysis.csv",
        "derived_from": "Fig. 2 paired delta source data",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "n=2 descriptive resampling envelope",
        "hardware_boundary": "not a board measurement",
        "notes": "Transparency analysis only; not a significance test.",
    },
    {
        "item_id": "paired_uncertainty_metadata",
        "manuscript_item": "Paired uncertainty analysis metadata",
        "source_path": "docs/paper_materials/submission_draft_paired_uncertainty_analysis.json",
        "derived_from": "run_paired_uncertainty_analysis.py",
        "source_data_scope": "machine-readable analysis metadata",
        "statistical_boundary": "non-inferential descriptive envelope",
        "hardware_boundary": "not a board measurement",
        "notes": "Records seed and resampling protocol.",
    },
    {
        "item_id": "ler_advantage_margin",
        "manuscript_item": "LER advantage-margin table",
        "source_path": "docs/paper_materials/submission_draft_ler_advantage_margin_analysis.csv",
        "derived_from": "source_data_fig02_main_results.csv and source_data_fig02_paired_deltas.csv",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "descriptive effect-size-style margin only",
        "hardware_boundary": "not a board measurement",
        "notes": "Does not provide confidence intervals, p-values or expanded-benchmark evidence.",
    },
    {
        "item_id": "ler_advantage_margin_metadata",
        "manuscript_item": "LER advantage-margin metadata",
        "source_path": "docs/paper_materials/submission_draft_ler_advantage_margin_analysis.json",
        "derived_from": "run_ler_advantage_margin_analysis.py",
        "source_data_scope": "machine-readable analysis metadata",
        "statistical_boundary": "descriptive effect-size-style margin only",
        "hardware_boundary": "not a board measurement",
        "notes": "Records source CSVs, scope and non-claims.",
    },
    {
        "item_id": "ler_advantage_margin_note",
        "manuscript_item": "LER advantage-margin reinforcement note",
        "source_path": "docs/paper_materials/投稿稿LER优势幅度分析记录.md",
        "derived_from": "run_ler_advantage_margin_analysis.py",
        "source_data_scope": "human-readable advantage-margin boundary note",
        "statistical_boundary": "not inferential evidence",
        "hardware_boundary": "not a board measurement",
        "notes": "Explains UKF-minus-Hybrid mean margin and delta/max SD boundaries.",
    },
    {
        "item_id": "fig03_ablation_mechanism",
        "manuscript_item": "Figure 3 ablation and mechanism summary",
        "source_path": "docs/figure_assets/submission_draft_python_figures/source_data_fig03_ablation_mechanism.csv",
        "derived_from": "preserved ablation and mechanism summaries",
        "source_data_scope": "manuscript figure source data",
        "statistical_boundary": "descriptive mechanism support only",
        "hardware_boundary": "not a board measurement",
        "notes": "Does not establish causal mechanism closure.",
    },
    {
        "item_id": "fig04_statcalib",
        "manuscript_item": "Figure 4 supplementary statistical-calibration analysis",
        "source_path": "docs/figure_assets/submission_draft_python_figures/source_data_fig04_statcalib.csv",
        "derived_from": "supplementary statistical-calibration comparison rows",
        "source_data_scope": "manuscript figure source data",
        "statistical_boundary": "supplementary bounded comparison only",
        "hardware_boundary": "not a board measurement",
        "notes": "Supports affine-contract substitutability, not comparator promotion.",
    },
    {
        "item_id": "fig05_validation_contract",
        "manuscript_item": "Figure 5 validation-contract summary",
        "source_path": "docs/figure_assets/submission_draft_python_figures/source_data_fig05_validation_contract.csv",
        "derived_from": "fast-path cost, fixed-point parity and runtime-discipline analyses",
        "source_data_scope": "manuscript figure source data",
        "statistical_boundary": "software validation summary only",
        "hardware_boundary": "not FPGA timing, resource or power evidence",
        "notes": "Summarizes software-backed checks and future hardware requirements.",
    },
    {
        "item_id": "controlled_oracle_affine",
        "manuscript_item": "Controlled nearest-syndrome, oracle-affine and wrapped-Gaussian sanity check",
        "source_path": "docs/paper_materials/submission_draft_controlled_oracle_affine_analysis.csv",
        "derived_from": "run_controlled_oracle_affine_analysis.py",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "one-step local-Gaussian sanity analysis",
        "hardware_boundary": "not a board measurement",
        "notes": "Includes a hard nearest-syndrome sanity reference; does not replace a formal nearest-lattice or sequence-level benchmark.",
    },
    {
        "item_id": "controlled_oracle_affine_metadata",
        "manuscript_item": "Controlled nearest-syndrome/oracle-affine metadata",
        "source_path": "docs/paper_materials/submission_draft_controlled_oracle_affine_analysis.json",
        "derived_from": "run_controlled_oracle_affine_analysis.py",
        "source_data_scope": "machine-readable analysis metadata",
        "statistical_boundary": "controlled local-Gaussian assumptions",
        "hardware_boundary": "not a board measurement",
        "notes": "Records assumptions and non-claim boundaries.",
    },
    {
        "item_id": "sequence_controlled_baseline",
        "manuscript_item": "Sequence-controlled nearest-syndrome/oracle/wrapped baseline analysis",
        "source_path": "docs/paper_materials/submission_draft_sequence_controlled_baseline_analysis.csv",
        "derived_from": "run_sequence_controlled_baseline_analysis.py",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "short-sequence controlled analysis",
        "hardware_boundary": "not a board measurement",
        "notes": "Includes a hard nearest-syndrome sanity reference; does not constitute an expanded benchmark.",
    },
    {
        "item_id": "sequence_controlled_baseline_metadata",
        "manuscript_item": "Sequence-controlled baseline metadata",
        "source_path": "docs/paper_materials/submission_draft_sequence_controlled_baseline_analysis.json",
        "derived_from": "run_sequence_controlled_baseline_analysis.py",
        "source_data_scope": "machine-readable analysis metadata",
        "statistical_boundary": "controlled short-sequence assumptions",
        "hardware_boundary": "not a board measurement",
        "notes": "Records protocol and boundary statements.",
    },
    {
        "item_id": "holdout_drift_stress",
        "manuscript_item": "Controlled holdout-drift stress diagnostic",
        "source_path": "docs/paper_materials/submission_draft_holdout_drift_stress_analysis.csv",
        "derived_from": "run_holdout_drift_stress_analysis.py",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "controlled diagnostic only",
        "hardware_boundary": "not a board measurement",
        "notes": "Does not prove trained-branch holdout generalization.",
    },
    {
        "item_id": "holdout_drift_stress_metadata",
        "manuscript_item": "Holdout-drift stress metadata",
        "source_path": "docs/paper_materials/submission_draft_holdout_drift_stress_analysis.json",
        "derived_from": "run_holdout_drift_stress_analysis.py",
        "source_data_scope": "machine-readable analysis metadata",
        "statistical_boundary": "diagnostic assumptions and protocol",
        "hardware_boundary": "not a board measurement",
        "notes": "Records diagnostic drift families and non-claims.",
    },
    {
        "item_id": "affine_local_validity_diagnostic",
        "manuscript_item": "Affine local-validity diagnostic",
        "source_path": "docs/paper_materials/submission_draft_affine_local_validity_diagnostic.csv",
        "derived_from": "run_affine_local_validity_diagnostic.py",
        "source_data_scope": "derived manuscript table source data",
        "statistical_boundary": "diagnostic readout only; not inferential evidence",
        "hardware_boundary": "not a board measurement",
        "notes": "Derives oracle-MSE headroom, naive wrapped-posterior branch risk and stale-commit risk from existing controlled CSVs.",
    },
    {
        "item_id": "affine_local_validity_diagnostic_metadata",
        "manuscript_item": "Affine local-validity diagnostic metadata",
        "source_path": "docs/paper_materials/submission_draft_affine_local_validity_diagnostic.json",
        "derived_from": "run_affine_local_validity_diagnostic.py",
        "source_data_scope": "machine-readable derived diagnostic metadata",
        "statistical_boundary": "not a confidence interval or p-value analysis",
        "hardware_boundary": "not a board measurement",
        "notes": "Records formulas, source files and non-claim boundaries.",
    },
    {
        "item_id": "affine_local_validity_diagnostic_note",
        "manuscript_item": "Affine local-validity diagnostic reinforcement note",
        "source_path": "docs/paper_materials/投稿稿affine_local_validity诊断记录.md",
        "derived_from": "run_affine_local_validity_diagnostic.py",
        "source_data_scope": "human-readable derived diagnostic boundary note",
        "statistical_boundary": "not inferential evidence",
        "hardware_boundary": "not a board measurement",
        "notes": "Explains oracle-affine headroom, branch-risk and stale-commit-risk readout boundaries.",
    },
    {
        "item_id": "commit_lag_sweep",
        "manuscript_item": "Controlled commit-lag sweep diagnostic",
        "source_path": "docs/paper_materials/submission_draft_commit_lag_sweep_analysis.csv",
        "derived_from": "run_commit_lag_sweep_analysis.py",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "controlled diagnostic only",
        "hardware_boundary": "not measured FPGA latency or source-vs-board agreement",
        "notes": "Sweeps simulation-step commit lag; does not prove trained-branch holdout generalization.",
    },
    {
        "item_id": "commit_lag_sweep_metadata",
        "manuscript_item": "Commit-lag sweep metadata",
        "source_path": "docs/paper_materials/submission_draft_commit_lag_sweep_analysis.json",
        "derived_from": "run_commit_lag_sweep_analysis.py",
        "source_data_scope": "machine-readable analysis metadata",
        "statistical_boundary": "diagnostic assumptions and protocol",
        "hardware_boundary": "not measured FPGA latency or source-vs-board agreement",
        "notes": "Records lag grid, simulation-step boundary and non-claims.",
    },
    {
        "item_id": "commit_lag_sweep_note",
        "manuscript_item": "Commit-lag sweep reinforcement note",
        "source_path": "docs/paper_materials/投稿稿commit_lag_sweep分析记录.md",
        "derived_from": "run_commit_lag_sweep_analysis.py",
        "source_data_scope": "human-readable diagnostic boundary note",
        "statistical_boundary": "not inferential evidence",
        "hardware_boundary": "not measured FPGA latency or source-vs-board agreement",
        "notes": "Explains stale-parameter sweep coverage and non-claim boundaries.",
    },
    {
        "item_id": "fast_path_cost",
        "manuscript_item": "Analytical fast-path operation-count model",
        "source_path": "docs/paper_materials/submission_draft_fast_path_cost_model.csv",
        "derived_from": "run_fast_path_cost_model.py",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "analytical cost model",
        "hardware_boundary": "not synthesis, timing, resource or power evidence",
        "notes": "Supports complexity discussion only.",
    },
    {
        "item_id": "fast_path_cost_metadata",
        "manuscript_item": "Fast-path cost model metadata",
        "source_path": "docs/paper_materials/submission_draft_fast_path_cost_model.json",
        "derived_from": "run_fast_path_cost_model.py",
        "source_data_scope": "machine-readable analysis metadata",
        "statistical_boundary": "analytical assumptions",
        "hardware_boundary": "not synthesis, timing, resource or power evidence",
        "notes": "Records operation-count assumptions.",
    },
    {
        "item_id": "fixed_point_parity",
        "manuscript_item": "Q4.20 software fixed-point parity",
        "source_path": "docs/paper_materials/submission_draft_fixed_point_parity_analysis.csv",
        "derived_from": "run_fixed_point_parity_analysis.py",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "software-emulation numerical check",
        "hardware_boundary": "not source-vs-board agreement",
        "notes": "Supports fixed-point plausibility only.",
    },
    {
        "item_id": "fixed_point_parity_metadata",
        "manuscript_item": "Fixed-point parity metadata",
        "source_path": "docs/paper_materials/submission_draft_fixed_point_parity_analysis.json",
        "derived_from": "run_fixed_point_parity_analysis.py",
        "source_data_scope": "machine-readable analysis metadata",
        "statistical_boundary": "software-emulation assumptions",
        "hardware_boundary": "not source-vs-board agreement",
        "notes": "Records Q-format and tolerance assumptions.",
    },
    {
        "item_id": "logical_channel_surrogate",
        "manuscript_item": "Residual-boundary Pauli-event surrogate",
        "source_path": "docs/paper_materials/submission_draft_logical_channel_surrogate_analysis.csv",
        "derived_from": "run_logical_channel_surrogate_analysis.py",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "surrogate half-lattice crossing analysis",
        "hardware_boundary": "not a board measurement",
        "notes": "Not finite-energy logical-channel fidelity or tomography.",
    },
    {
        "item_id": "logical_channel_surrogate_metadata",
        "manuscript_item": "Logical-channel surrogate metadata",
        "source_path": "docs/paper_materials/submission_draft_logical_channel_surrogate_analysis.json",
        "derived_from": "run_logical_channel_surrogate_analysis.py",
        "source_data_scope": "machine-readable analysis metadata",
        "statistical_boundary": "surrogate formula and assumptions",
        "hardware_boundary": "not a board measurement",
        "notes": "Records formula boundaries and non-claims.",
    },
    {
        "item_id": "lattice_logical_channel_sanity",
        "manuscript_item": "Lattice logical-channel sanity summary",
        "source_path": "docs/paper_materials/submission_draft_lattice_logical_channel_sanity.csv",
        "derived_from": "run_lattice_logical_channel_sanity.py",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "method-level surrogate aggregation only",
        "hardware_boundary": "not a board measurement",
        "notes": "Not finite-energy logical-channel fidelity, tomography or hardware fidelity.",
    },
    {
        "item_id": "lattice_logical_channel_sanity_metadata",
        "manuscript_item": "Lattice logical-channel sanity metadata",
        "source_path": "docs/paper_materials/submission_draft_lattice_logical_channel_sanity.json",
        "derived_from": "run_lattice_logical_channel_sanity.py",
        "source_data_scope": "machine-readable surrogate aggregation metadata",
        "statistical_boundary": "method-level surrogate aggregation only",
        "hardware_boundary": "not a board measurement",
        "notes": "Records formula source, scope and non-claims.",
    },
    {
        "item_id": "lattice_logical_channel_sanity_note",
        "manuscript_item": "Lattice logical-channel sanity reinforcement note",
        "source_path": "docs/paper_materials/投稿稿lattice_logical_channel_sanity记录.md",
        "derived_from": "run_lattice_logical_channel_sanity.py",
        "source_data_scope": "human-readable surrogate aggregation boundary note",
        "statistical_boundary": "not inferential evidence",
        "hardware_boundary": "not a board measurement",
        "notes": "Explains method-level p_any and F_avg_surr boundaries.",
    },
    {
        "item_id": "finite_energy_channel_sanity",
        "manuscript_item": "Finite-squeezing toy-channel sanity check",
        "source_path": "docs/paper_materials/submission_draft_finite_energy_channel_sanity.csv",
        "derived_from": "run_finite_energy_channel_sanity.py",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "toy measurement-channel sanity only",
        "hardware_boundary": "not a board measurement",
        "notes": "Not calibrated finite-energy logical-channel fidelity, process tomography or hardware fidelity.",
    },
    {
        "item_id": "finite_energy_channel_sanity_metadata",
        "manuscript_item": "Finite-squeezing toy-channel sanity metadata",
        "source_path": "docs/paper_materials/submission_draft_finite_energy_channel_sanity.json",
        "derived_from": "run_finite_energy_channel_sanity.py",
        "source_data_scope": "machine-readable toy-channel metadata",
        "statistical_boundary": "toy measurement-channel assumptions",
        "hardware_boundary": "not a board measurement",
        "notes": "Records finite-squeezing deltas, seed, sample count and non-claims.",
    },
    {
        "item_id": "finite_energy_channel_sanity_note",
        "manuscript_item": "Finite-squeezing toy-channel reinforcement note",
        "source_path": "docs/paper_materials/投稿稿finite_energy_channel_sanity记录.md",
        "derived_from": "run_finite_energy_channel_sanity.py",
        "source_data_scope": "human-readable toy-channel boundary note",
        "statistical_boundary": "not inferential evidence",
        "hardware_boundary": "not a board measurement",
        "notes": "Explains toy finite-squeezing measurement-channel boundary.",
    },
    {
        "item_id": "runtime_discipline",
        "manuscript_item": "Runtime-discipline counters",
        "source_path": "docs/paper_materials/submission_draft_runtime_discipline_summary.csv",
        "derived_from": "run_runtime_discipline_summary.py",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "software protocol observability",
        "hardware_boundary": "not board commit latency or reliability",
        "notes": "Does not prove hardware rollback or timing behaviour.",
    },
    {
        "item_id": "runtime_discipline_metadata",
        "manuscript_item": "Runtime-discipline metadata",
        "source_path": "docs/paper_materials/submission_draft_runtime_discipline_summary.json",
        "derived_from": "run_runtime_discipline_summary.py",
        "source_data_scope": "machine-readable analysis metadata",
        "statistical_boundary": "software protocol observability",
        "hardware_boundary": "not board commit latency or reliability",
        "notes": "Records source rows and boundary statements.",
    },
    {
        "item_id": "gkp_boundary_sensitivity",
        "manuscript_item": "GKP boundary-sensitivity analytical bridge",
        "source_path": "docs/paper_materials/submission_draft_gkp_boundary_sensitivity.csv",
        "derived_from": "run_gkp_boundary_sensitivity_analysis.py",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "analytical residual-scale bridge",
        "hardware_boundary": "not a board measurement",
        "notes": "Not a finite-energy channel simulation.",
    },
    {
        "item_id": "gkp_boundary_sensitivity_metadata",
        "manuscript_item": "GKP boundary-sensitivity metadata",
        "source_path": "docs/paper_materials/submission_draft_gkp_boundary_sensitivity.json",
        "derived_from": "run_gkp_boundary_sensitivity_analysis.py",
        "source_data_scope": "machine-readable analysis metadata",
        "statistical_boundary": "analytical assumptions and formulas",
        "hardware_boundary": "not a board measurement",
        "notes": "Records formula and non-claim boundaries.",
    },
    {
        "item_id": "metric_readiness",
        "manuscript_item": "Metric-readiness matrix",
        "source_path": "docs/paper_materials/submission_draft_metric_readiness_matrix.csv",
        "derived_from": "manual manuscript metric-readiness table",
        "source_data_scope": "manuscript table source data",
        "statistical_boundary": "readiness classification",
        "hardware_boundary": "records missing hardware measurement status",
        "notes": "Does not add any metric measurement.",
    },
    {
        "item_id": "metric_readiness_metadata",
        "manuscript_item": "Metric-readiness metadata",
        "source_path": "docs/paper_materials/submission_draft_metric_readiness_matrix.json",
        "derived_from": "manual manuscript metric-readiness table",
        "source_data_scope": "machine-readable boundary metadata",
        "statistical_boundary": "readiness classification",
        "hardware_boundary": "records missing hardware measurement status",
        "notes": "Keeps latency, resource and board validation as missing.",
    },
    {
        "item_id": "literature_metric_crosswalk",
        "manuscript_item": "Literature metric crosswalk for external comparison",
        "source_path": "docs/paper_materials/submission_draft_literature_metric_crosswalk.csv",
        "derived_from": "zotero_literature_review_cards.md and active manuscript comparison axes",
        "source_data_scope": "manuscript literature-positioning source data",
        "statistical_boundary": "not normalized across code families or metrics",
        "hardware_boundary": "records prior hardware metrics only, not this manuscript's board evidence",
        "notes": "Supports related-work positioning; not a leaderboard or experimental result.",
    },
    {
        "item_id": "literature_metric_crosswalk_metadata",
        "manuscript_item": "Literature metric crosswalk metadata",
        "source_path": "docs/paper_materials/submission_draft_literature_metric_crosswalk.json",
        "derived_from": "build_submission_draft_literature_metric_crosswalk.py",
        "source_data_scope": "machine-readable literature-positioning metadata",
        "statistical_boundary": "not inferential evidence",
        "hardware_boundary": "not this manuscript's hardware validation",
        "notes": "Records non-claim boundaries for cited comparison metrics.",
    },
    {
        "item_id": "closest_work_positioning",
        "manuscript_item": "Closest-work positioning table",
        "source_path": "docs/paper_materials/submission_draft_closest_work_positioning.csv",
        "derived_from": "build_submission_draft_closest_work_positioning.py",
        "source_data_scope": "manuscript literature-positioning source data",
        "statistical_boundary": "not normalized across code families or validation layers",
        "hardware_boundary": "not this manuscript's hardware validation",
        "notes": "Positions the manuscript relative to adjacent analog-GKP, calibration, learned-decoder and real-time-FPGA work.",
    },
    {
        "item_id": "closest_work_positioning_metadata",
        "manuscript_item": "Closest-work positioning metadata",
        "source_path": "docs/paper_materials/submission_draft_closest_work_positioning.json",
        "derived_from": "build_submission_draft_closest_work_positioning.py",
        "source_data_scope": "machine-readable literature-positioning metadata",
        "statistical_boundary": "not inferential evidence",
        "hardware_boundary": "not this manuscript's hardware validation",
        "notes": "Records closest-work families, citation groups and non-claim boundaries.",
    },
    {
        "item_id": "closest_work_positioning_note",
        "manuscript_item": "Closest-work positioning reinforcement note",
        "source_path": "docs/paper_materials/投稿稿closest_work_positioning记录.md",
        "derived_from": "build_submission_draft_closest_work_positioning.py",
        "source_data_scope": "human-readable positioning boundary note",
        "statistical_boundary": "not result evidence",
        "hardware_boundary": "not hardware validation",
        "notes": "Explains why the closest-work table is positioning rather than a leaderboard.",
    },
    {
        "item_id": "source_data_coverage_matrix",
        "manuscript_item": "Source-data coverage matrix",
        "source_path": "docs/paper_materials/submission_draft_source_data_coverage_matrix.csv",
        "derived_from": "build_submission_draft_source_data_coverage_matrix.py",
        "source_data_scope": "manuscript coverage table source data",
        "statistical_boundary": "coverage classification only",
        "hardware_boundary": "not hardware validation",
        "notes": "Separates mechanically checked result tables from planning and boundary surfaces.",
    },
    {
        "item_id": "source_data_coverage_matrix_metadata",
        "manuscript_item": "Source-data coverage metadata",
        "source_path": "docs/paper_materials/submission_draft_source_data_coverage_matrix.json",
        "derived_from": "build_submission_draft_source_data_coverage_matrix.py",
        "source_data_scope": "machine-readable coverage metadata",
        "statistical_boundary": "coverage classification only",
        "hardware_boundary": "not hardware validation",
        "notes": "Records coverage groups and non-claim boundaries.",
    },
    {
        "item_id": "source_data_coverage_matrix_note",
        "manuscript_item": "Source-data coverage reinforcement note",
        "source_path": "docs/paper_materials/投稿稿source_data覆盖矩阵记录.md",
        "derived_from": "build_submission_draft_source_data_coverage_matrix.py",
        "source_data_scope": "human-readable coverage boundary note",
        "statistical_boundary": "not result evidence",
        "hardware_boundary": "not hardware validation",
        "notes": "Explains checked-table coverage and explicit non-claim boundaries.",
    },
    {
        "item_id": "benchmark_expansion_protocol",
        "manuscript_item": "Benchmark expansion protocol",
        "source_path": "docs/paper_materials/submission_draft_benchmark_expansion_protocol.csv",
        "derived_from": "Fig. 2 paired delta source data and predeclared manuscript upgrade gates",
        "source_data_scope": "manuscript benchmark-expansion planning source data",
        "statistical_boundary": "planning protocol only; not inferential evidence",
        "hardware_boundary": "not hardware timing, resource, power or source-vs-board evidence",
        "notes": "Records repeat budget, holdout families and upgrade gates for future execution.",
    },
    {
        "item_id": "benchmark_expansion_protocol_metadata",
        "manuscript_item": "Benchmark expansion protocol metadata",
        "source_path": "docs/paper_materials/submission_draft_benchmark_expansion_protocol.json",
        "derived_from": "build_submission_draft_benchmark_expansion_protocol.py",
        "source_data_scope": "machine-readable benchmark-expansion planning metadata",
        "statistical_boundary": "does not provide CI, p-value or robustness proof",
        "hardware_boundary": "not hardware timing, resource, power or source-vs-board evidence",
        "notes": "Records non-claims for repeat expansion, holdout expansion and runtime provenance.",
    },
    {
        "item_id": "runner_smoke_pair",
        "manuscript_item": "Runner smoke-pair feasibility summary",
        "source_path": "docs/paper_materials/submission_draft_runner_smoke_pair.csv",
        "derived_from": "runs/paper_submission_pilot/smoke_static_ukf_hybrid_r1",
        "source_data_scope": "manuscript planning and feasibility source data",
        "statistical_boundary": "one-scenario one-repeat smoke pair only",
        "hardware_boundary": "not hardware timing, resource, power or source-vs-board evidence",
        "notes": "Records runner feasibility for future repeat-expanded execution; not a main-text performance result.",
    },
    {
        "item_id": "runner_smoke_pair_metadata",
        "manuscript_item": "Runner smoke-pair feasibility metadata",
        "source_path": "docs/paper_materials/submission_draft_runner_smoke_pair.json",
        "derived_from": "build_submission_draft_runner_smoke_pair.py",
        "source_data_scope": "machine-readable runner-feasibility metadata",
        "statistical_boundary": "not CI, p-value, standard error or robustness evidence",
        "hardware_boundary": "not hardware timing, resource, power or source-vs-board evidence",
        "notes": "Records source hashes and non-claim boundaries for the smoke-pair output.",
    },
    {
        "item_id": "runner_smoke_matrix",
        "manuscript_item": "All-scenario runner smoke-matrix feasibility summary",
        "source_path": "docs/paper_materials/submission_draft_runner_smoke_matrix.csv",
        "derived_from": "runs/paper_submission_pilot/smoke_all_scenarios_ukf_hybrid_r2_20260703_093537",
        "source_data_scope": "manuscript planning and feasibility source data",
        "statistical_boundary": "all-scenario short-run pilot only",
        "hardware_boundary": "not hardware timing, resource, power or source-vs-board evidence",
        "notes": "Records runner feasibility for the planned repeat-expanded UKF-vs-Hybrid execution; not a main-text performance result.",
    },
    {
        "item_id": "runner_smoke_matrix_metadata",
        "manuscript_item": "All-scenario runner smoke-matrix feasibility metadata",
        "source_path": "docs/paper_materials/submission_draft_runner_smoke_matrix.json",
        "derived_from": "build_submission_draft_runner_smoke_matrix.py",
        "source_data_scope": "machine-readable runner-feasibility metadata",
        "statistical_boundary": "not CI, p-value, standard error or robustness evidence",
        "hardware_boundary": "not hardware timing, resource, power or source-vs-board evidence",
        "notes": "Records source hashes, filters and non-claim boundaries for the all-scenario smoke-matrix output.",
    },
    {
        "item_id": "phase_a_repeat_plan",
        "manuscript_item": "Phase A repeat-expanded execution plan",
        "source_path": "docs/paper_materials/submission_draft_phase_a_repeat_plan.csv",
        "derived_from": "build_submission_draft_phase_a_repeat_plan.py",
        "source_data_scope": "manuscript planning and execution-command source data",
        "statistical_boundary": "planning protocol only; not inferential evidence",
        "hardware_boundary": "not hardware timing, resource, power or source-vs-board evidence",
        "notes": "Records formal-length chunks, smoke feasibility rows, commands and post-run artifact requirements.",
    },
    {
        "item_id": "phase_a_repeat_plan_metadata",
        "manuscript_item": "Phase A repeat-expanded execution plan metadata",
        "source_path": "docs/paper_materials/submission_draft_phase_a_repeat_plan.json",
        "derived_from": "build_submission_draft_phase_a_repeat_plan.py",
        "source_data_scope": "machine-readable planning metadata",
        "statistical_boundary": "does not provide CI, p-value or robustness proof",
        "hardware_boundary": "not hardware timing, resource, power or source-vs-board evidence",
        "notes": "Records scenario/mode units and non-claim boundaries for planned repeat expansion.",
    },
    {
        "item_id": "phase_a_repeat_summary",
        "manuscript_item": "Completed Phase A repeat-run summary",
        "source_path": "docs/paper_materials/submission_draft_phase_a_repeat_summary.csv",
        "derived_from": "build_submission_draft_phase_a_repeat_summary.py and runs/paper_submission_phase_a",
        "source_data_scope": "completed-run source summary when available",
        "statistical_boundary": "no CI, p-value or significance without separate paired interval analysis",
        "hardware_boundary": "not hardware timing, resource, power or source-vs-board evidence",
        "notes": "Empty if no Phase A runs exist; short-run rows remain feasibility-only.",
    },
    {
        "item_id": "phase_a_repeat_summary_metadata",
        "manuscript_item": "Completed Phase A repeat-run summary metadata",
        "source_path": "docs/paper_materials/submission_draft_phase_a_repeat_summary.json",
        "derived_from": "build_submission_draft_phase_a_repeat_summary.py",
        "source_data_scope": "machine-readable completed-run summary metadata",
        "statistical_boundary": "does not provide CI, p-value or robustness proof",
        "hardware_boundary": "not hardware timing, resource, power or source-vs-board evidence",
        "notes": "Records run-root scan status and row-level non-claim boundaries.",
    },
    {
        "item_id": "phase_a_paired_interval",
        "manuscript_item": "Formal Phase A one-scenario paired-interval analysis",
        "source_path": "docs/paper_materials/submission_draft_phase_a_paired_interval_analysis.csv",
        "derived_from": "run_phase_a_paired_interval_analysis.py and submission_draft_phase_a_repeat_summary.csv",
        "source_data_scope": "completed formal scenario interval source data",
        "statistical_boundary": "one completed scenario only; not all-scenario repeat-expanded evidence or p-value evidence",
        "hardware_boundary": "not hardware timing, resource, power or source-vs-board evidence",
        "notes": "Records paired-t and bootstrap interval lower bounds for completed formal-length scenario rows.",
    },
    {
        "item_id": "phase_a_paired_interval_metadata",
        "manuscript_item": "Formal Phase A one-scenario paired-interval metadata",
        "source_path": "docs/paper_materials/submission_draft_phase_a_paired_interval_analysis.json",
        "derived_from": "run_phase_a_paired_interval_analysis.py",
        "source_data_scope": "machine-readable paired-interval analysis metadata",
        "statistical_boundary": "does not compute p-values or prove holdout robustness",
        "hardware_boundary": "does not provide hardware validation",
        "notes": "Records source file, bootstrap seed, non-claims and row-level claim boundary.",
    },
    {
        "item_id": "phase_a_upgrade_gate",
        "manuscript_item": "Phase A statistical and hardware validation-threshold gate",
        "source_path": "docs/paper_materials/submission_draft_phase_a_upgrade_gate.csv",
        "derived_from": "build_submission_draft_phase_a_upgrade_gate.py",
        "source_data_scope": "validation-threshold boundary source data",
        "statistical_boundary": "validation-threshold gate only; not inferential evidence",
        "hardware_boundary": "records missing hardware measurement status",
        "notes": "Separates current descriptive wording from repeat-expanded, holdout and hardware validation requirements.",
    },
    {
        "item_id": "phase_a_upgrade_gate_metadata",
        "manuscript_item": "Phase A validation-threshold metadata",
        "source_path": "docs/paper_materials/submission_draft_phase_a_upgrade_gate.json",
        "derived_from": "build_submission_draft_phase_a_upgrade_gate.py",
        "source_data_scope": "machine-readable validation-threshold boundary metadata",
        "statistical_boundary": "does not compute confidence intervals or p-values",
        "hardware_boundary": "does not provide hardware validation",
        "notes": "Records source files, non-claims and row-level upgrade conditions.",
    },
    {
        "item_id": "row_provenance_manifest",
        "manuscript_item": "Row-level provenance manifest for main software-HIL benchmark",
        "source_path": "docs/paper_materials/submission_draft_row_provenance_manifest.csv",
        "derived_from": "build_submission_draft_row_provenance_manifest.py and preserved T24 software-HIL run metadata",
        "source_data_scope": "row-level manuscript benchmark provenance",
        "statistical_boundary": "source trace only; not inferential evidence",
        "hardware_boundary": "not board timing, resource, power or source-vs-board evidence",
        "notes": "Records scenario/mode/repeat/seed, source run path and hashes for existing benchmark rows.",
    },
    {
        "item_id": "row_provenance_manifest_metadata",
        "manuscript_item": "Row-level provenance metadata",
        "source_path": "docs/paper_materials/submission_draft_row_provenance_manifest.json",
        "derived_from": "build_submission_draft_row_provenance_manifest.py",
        "source_data_scope": "machine-readable row-level provenance metadata",
        "statistical_boundary": "not CI, p-value, standard error or robustness evidence",
        "hardware_boundary": "not board timing, resource, power or source-vs-board evidence",
        "notes": "Records manifest scope, excluded hash closure and non-claim boundaries.",
    },
    {
        "item_id": "row_provenance_manifest_note",
        "manuscript_item": "Row-level provenance reinforcement note",
        "source_path": "docs/paper_materials/投稿稿row_level_provenance补强记录.md",
        "derived_from": "build_submission_draft_row_provenance_manifest.py",
        "source_data_scope": "human-readable provenance boundary note",
        "statistical_boundary": "not inferential evidence",
        "hardware_boundary": "not hardware provenance",
        "notes": "Explains row-level provenance coverage and non-claim boundaries.",
    },
    {
        "item_id": "cnn_branch_details",
        "manuscript_item": "CNN residual branch method details",
        "source_path": "docs/paper_materials/submission_draft_cnn_branch_method_details.csv",
        "derived_from": "preserved manuscript method details",
        "source_data_scope": "manuscript method table source data",
        "statistical_boundary": "method specification only",
        "hardware_boundary": "not a board measurement",
        "notes": "Does not rerun training or prove full reproducibility.",
    },
    {
        "item_id": "cnn_branch_details_metadata",
        "manuscript_item": "CNN residual branch method metadata",
        "source_path": "docs/paper_materials/submission_draft_cnn_branch_method_details.json",
        "derived_from": "preserved manuscript method details",
        "source_data_scope": "machine-readable method boundary metadata",
        "statistical_boundary": "method specification only",
        "hardware_boundary": "not a board measurement",
        "notes": "Records branch details and non-claims.",
    },
    {
        "item_id": "figure_manifest",
        "manuscript_item": "Figure output and source-data manifest",
        "source_path": "docs/figure_assets/submission_draft_python_figures/figure_manifest.json",
        "derived_from": "build_submission_draft_figures.py",
        "source_data_scope": "figure package manifest",
        "statistical_boundary": "inherits per-figure source-data limits",
        "hardware_boundary": "not a board measurement",
        "notes": "Lists generated figure outputs and source data.",
    },
    {
        "item_id": "figure_source_map",
        "manuscript_item": "Figure source map",
        "source_path": "docs/figure_assets/submission_draft_python_figures/figure_source_map.csv",
        "derived_from": "build_submission_draft_figures.py",
        "source_data_scope": "figure source mapping",
        "statistical_boundary": "inherits per-figure source-data limits",
        "hardware_boundary": "not a board measurement",
        "notes": "Maps figures to source tables and non-claim boundaries.",
    },
]

SCRIPTS = [
    "docs/figure_assets/submission_draft_python_figures/build_submission_draft_figures.py",
    "docs/figure_assets/submission_draft_python_figures/audit_submission_draft_source_data.py",
    "docs/figure_assets/submission_draft_python_figures/audit_submission_draft_symbol_boundary.py",
    "docs/paper_materials/run_controlled_oracle_affine_analysis.py",
    "docs/paper_materials/run_sequence_controlled_baseline_analysis.py",
    "docs/paper_materials/run_holdout_drift_stress_analysis.py",
    "docs/paper_materials/run_affine_local_validity_diagnostic.py",
    "docs/paper_materials/run_commit_lag_sweep_analysis.py",
    "docs/paper_materials/run_fast_path_cost_model.py",
    "docs/paper_materials/run_fixed_point_parity_analysis.py",
    "docs/paper_materials/run_logical_channel_surrogate_analysis.py",
    "docs/paper_materials/run_lattice_logical_channel_sanity.py",
    "docs/paper_materials/run_finite_energy_channel_sanity.py",
    "docs/paper_materials/run_runtime_discipline_summary.py",
    "docs/paper_materials/run_gkp_boundary_sensitivity_analysis.py",
    "docs/paper_materials/run_paired_uncertainty_analysis.py",
    "docs/paper_materials/run_ler_advantage_margin_analysis.py",
    "docs/paper_materials/run_phase_a_paired_interval_analysis.py",
    "docs/paper_materials/build_submission_draft_literature_metric_crosswalk.py",
    "docs/paper_materials/build_submission_draft_closest_work_positioning.py",
    "docs/paper_materials/build_submission_draft_source_data_coverage_matrix.py",
    "docs/paper_materials/build_submission_draft_benchmark_expansion_protocol.py",
    "docs/paper_materials/build_submission_draft_runner_smoke_pair.py",
    "docs/paper_materials/build_submission_draft_runner_smoke_matrix.py",
    "docs/paper_materials/build_submission_draft_phase_a_repeat_plan.py",
    "docs/paper_materials/build_submission_draft_phase_a_repeat_summary.py",
    "docs/paper_materials/build_submission_draft_phase_a_upgrade_gate.py",
    "docs/paper_materials/build_submission_draft_row_provenance_manifest.py",
]


def sha256_file(path: Path) -> str:
    digest = hashlib.sha256()
    with path.open("rb") as fh:
        for chunk in iter(lambda: fh.read(1024 * 1024), b""):
            digest.update(chunk)
    return digest.hexdigest()


def build_rows() -> list[dict[str, str]]:
    rows: list[dict[str, str]] = []
    for source in SOURCES:
        path = ROOT / source["source_path"]
        if not path.is_file():
            raise FileNotFoundError(source["source_path"])
        row = dict(source)
        row["sha256"] = sha256_file(path)
        row["size_bytes"] = str(path.stat().st_size)
        rows.append(row)

    for script_path in SCRIPTS:
        path = ROOT / script_path
        if not path.is_file():
            raise FileNotFoundError(script_path)
        rows.append(
            {
                "item_id": Path(script_path).stem,
                "manuscript_item": "Generator or audit script",
                "source_path": script_path,
                "sha256": sha256_file(path),
                "size_bytes": str(path.stat().st_size),
                "derived_from": "repository source script",
                "source_data_scope": "script provenance",
                "statistical_boundary": "does not add evidence by itself",
                "hardware_boundary": "not a board measurement",
                "notes": "Included so generated manuscript source data can be traced to scripts.",
            }
        )
    return rows


def main() -> None:
    rows = build_rows()
    fieldnames = [
        "item_id",
        "manuscript_item",
        "source_path",
        "sha256",
        "size_bytes",
        "derived_from",
        "source_data_scope",
        "statistical_boundary",
        "hardware_boundary",
        "notes",
    ]
    with OUT_CSV.open("w", newline="", encoding="utf-8") as fh:
        writer = csv.DictWriter(fh, fieldnames=fieldnames)
        writer.writeheader()
        writer.writerows(rows)
    OUT_JSON.write_text(
        json.dumps(
            {
                "manifest_scope": (
                    "File-level hashes for manuscript-facing source CSV/JSON "
                    "files and generator or audit scripts only."
                ),
                "non_claims": [
                    "not a recursive hash closure over historical run directories",
                    "not full training reproducibility evidence",
                    "not hardware provenance",
                    "not inferential statistical evidence",
                ],
                "rows": rows,
            },
            indent=2,
            ensure_ascii=False,
        )
        + "\n",
        encoding="utf-8",
    )
    print(json.dumps({"status": "ok", "rows": len(rows), "csv": str(OUT_CSV), "json": str(OUT_JSON)}))


if __name__ == "__main__":
    main()
